spring:
  application:
    name: app
  datasource:
    url: jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQLDATABASE}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${MYSQLUSER}
    password: ${MYSQLPASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update  # puedes usar 'create' o 'update' según necesites
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
server:
  port: ${PORT:8080}
logging:
  level:
    org:
      hibernate:
        orm:
          connections:
            pooling: warn
      springframework:
        security: debug
